// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Comment struct {
	ID        int64
	Name      string
	Content   string
	Slug      string
	CreatedAt sql.NullTime
	ParentID  sql.NullInt64
}
