// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
)

const createComment = `-- name: CreateComment :exec
    


INSERT INTO comments (name, content, slug, parent_id) VALUES (?, ?, ?, ?)
`

type CreateCommentParams struct {
	Name     string
	Content  string
	Slug     string
	ParentID sql.NullInt64
}

// WITH RECURSIVE CommentHierarchy AS (
//
//	SELECT id, name, content, slug, created_at, parent_id, 0 AS depth, name as path
//	FROM comments ch
//	WHERE ch.parent_id IS NULL AND ch.slug = '/writing/2-types-of-work'
//	UNION ALL
//	SELECT c.id, c.name, c.content, c.slug, c.created_at, c.parent_id, ch.depth + 1, ch.path || ' > ' || c.name
//	FROM comments c
//	JOIN CommentHierarchy ch ON c.parent_id = ch.id
//
// )
// SELECT * FROM CommentHierarchy;
func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) error {
	_, err := q.db.ExecContext(ctx, createComment,
		arg.Name,
		arg.Content,
		arg.Slug,
		arg.ParentID,
	)
	return err
}

const deleteComment = `-- name: DeleteComment :exec

DELETE FROM comments WHERE id = ?
`

// INSERT INTO comments (name, content, slug, parent_id) VALUES ('adem', 'yo waddup', '/writing/2-types-of-work', NULL);
func (q *Queries) DeleteComment(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteComment, id)
	return err
}

const getCommentsBySlug = `-- name: GetCommentsBySlug :many
WITH RECURSIVE CommentHierarchy AS (
    SELECT id, name, content, slug, created_at, parent_id, 0 AS depth, printf('%020d', id) AS path
    FROM comments ch
    WHERE ch.parent_id IS NULL AND ch.slug = ?

    UNION ALL
    
    SELECT c.id, c.name, c.content, c.slug, c.created_at, c.parent_id, ch.depth + 1, ch.path || '.' || printf('%020d', c.id)
    FROM comments c
    JOIN CommentHierarchy ch ON c.parent_id = ch.id
) 
SELECT id, name, content, slug, created_at, parent_id, depth, path FROM CommentHierarchy
ORDER BY path, created_at
`

type GetCommentsBySlugRow struct {
	ID        int64
	Name      string
	Content   string
	Slug      string
	CreatedAt sql.NullTime
	ParentID  sql.NullInt64
	Depth     int64
	Path      sql.NullString
}

func (q *Queries) GetCommentsBySlug(ctx context.Context, slug string) ([]GetCommentsBySlugRow, error) {
	rows, err := q.db.QueryContext(ctx, getCommentsBySlug, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCommentsBySlugRow
	for rows.Next() {
		var i GetCommentsBySlugRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Content,
			&i.Slug,
			&i.CreatedAt,
			&i.ParentID,
			&i.Depth,
			&i.Path,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateComment = `-- name: UpdateComment :exec
UPDATE comments SET content = ? WHERE id = ?
`

type UpdateCommentParams struct {
	Content string
	ID      int64
}

func (q *Queries) UpdateComment(ctx context.Context, arg UpdateCommentParams) error {
	_, err := q.db.ExecContext(ctx, updateComment, arg.Content, arg.ID)
	return err
}
