name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 134.122.82.20
          username: kdiffin
          key: ${{ secrets.DO_SSH_KEY }}
          passphrase: ${{ secrets.DO_SSH_KEY_PASSPHRASE }}

          script: |
            cd ~/portfolio
            git pull
            npm run css:build
            sqlc generate
            go build -o portfolio ./cmd/web
            sudo systemctl restart portfolio